yarnPath: .yarn/releases/yarn-3.1.1.cjs
nodeLinker: node-modules

packageExtensions:
  "@octokit/plugin-throttling@*":
    dependencies:
      "@octokit/core": "*"
  "@parcel/workers@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/fs@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/cache@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/package-manager@*":
    dependencies:
      "@parcel/core": "*"
  "sass-loader@*":
    dependencies:
      "webpack": "*"