nodeLinker: node-modules

packageExtensions:
  "@octokit/plugin-throttling@*":
    dependencies:
      "@octokit/core": "*"
  "@parcel/cache@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/fs@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/package-manager@*":
    dependencies:
      "@parcel/core": "*"
  "@parcel/workers@*":
    dependencies:
      "@parcel/core": "*"
  sass-loader@*:
    dependencies:
      webpack: "*"

yarnPath: .yarn/releases/yarn-3.6.4.cjs
