name: Release

on: [push]

env:
  GH_TOKEN: "${{ secrets.GH_TOKEN }}"

jobs:
  release:
    name: Release Train
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git fetch --tags

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: mbround18
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build FoundryVTT Docker
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          file: ./Dockerfile
          push: false
          tags: mbround18/foundryvtt-docker:latest

      - name: Create Release
        env:
          IMAGE: mbround18/foundryvtt-docker
        uses: mbround18/auto@v1.4.0
        with:
          token: ${{ secrets.GH_TOKEN }}
