name: Release

on: [push]

# env:
#   GH_TOKEN: "${{ secrets.GH_TOKEN }}"

jobs:
  release:
    name: Release Train
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      statuses: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ github.token }}

      - run: git pull && git fetch --tags

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: mbround18
          password: ${{ secrets.DOCKER_TOKEN }}

      - run: docker compose build

      - name: Create Release
        env:
          IMAGE: mbround18/foundryvtt-docker
        uses: mbround18/auto@v1.5.0
        with:
          token: ${{ github.token }}
