name: Release

on: [push]

# env:
#   GH_TOKEN: "${{ secrets.GH_TOKEN }}"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"

      - name: Install Deps
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Compile to binary
        run: yarn compile

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  release:
    name: Release Train
    needs: [build]
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      statuses: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ github.token }}

      - run: git pull && git fetch --tags

      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: mbround18
          password: ${{ secrets.DOCKER_TOKEN }}

      - run: docker compose build

      - name: Create Release
        env:
          IMAGE: mbround18/foundryvtt-docker
        uses: mbround18/auto@v1.5.0
        with:
          token: ${{ github.token }}
